platform: x86: PMC IPC depends on ACPI
This patch solves:

on x86_64:

when CONFIG_ACPI is not enabled:

../drivers/mfd/intel_soc_pmic_bxtwc.c: In function 'bxtwc_probe':
../drivers/mfd/intel_soc_pmic_bxtwc.c:342:2:
    error: implicit declaration of function 'acpi_evaluate_integer' [-Werror=implicit-function-declaration]
        status = acpi_evaluate_integer(handle, "_HRV", NULL, &hrv);
        ^

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Lee Jones <lee.jones@linaro.org>